### ISSUE TITLE
Don't use ServiceLocatorAwareInterface/Trait

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#10]
See omeka/omeka-s#554

**Comment by zerocrates** [comment]
Note this doesn't mean that CsvFile can't use the ServiceLocator, it just shouldn't implement that interface or use that trait.

**Comment by patrickmj** [comment]
So, would it just implement its own getter and setter for ServiceLocator?

**Comment by zerocrates** [comment]
Since you're already injecting it through the constructor, just a property is probably sufficient.
