### ISSUE TITLE
Testing DanielKM's enhancements.

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#106]
A lot of pull requests and features have come in from @Daniel-KM . They largely reflect the features that he has added in his fork of the Classic plugin for CSV Import. I think it makes sense for these to all be in one place for the S version of the module. That means, though, lots of testing through the different updates for our user testing team.

It will make sense to uninstall CSVImport. Then, switch to the branch `danielkm`, where I'm pulling in all his work on this repo. Then install that new code that includes his features. He's put in information about features in the README, so that will be a good starting place for what to look at.

Questions, concerns, bugs, etc. should come in as distinct issues on this repo, but not as comments on this testing issue.

**Comment by mebrett** [comment]
Does it matter which branch of the core?

**Comment by Daniel-KM** [comment]
Note that there is a light update in FileSideload and Mapping too if you try to csv-import them.

**Comment by patrickmj** [comment]
Thanks. the FileSideload changes were already there in master, but this reminded me to pull in the Mapping stuff, too.

**Comment by patrickmj** [comment]
@mebrett probably the latest develop of core is best.

**Comment by Daniel-KM** [comment]
There is the https://github.com/omeka-s-modules/FileSideload/pull/8 too (the other was for a fix), even if some commits were common.

**Comment by patrickmj** [comment]
Thanks. that's now also in master

**Comment by Daniel-KM** [comment]
I added the possibility to import directly [TSV](https://en.wikipedia.org/wiki/Tab-separated_values) (tab separated value) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/eef88daf30775dbada50cacff71f851ca44a3634) and [ODS](http://opendocumentformat.org/aboutODF) (OpenDocument Spreadsheet) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/e9c77cb71a10acd63cf3efd617e90ae2f14938c0).

Note that there is now a dependency, so I added a gulp task to create the zip.

There is a quick test with an [ods file](https://github.com/Daniel-KM/Omeka-S-module-CSVImport/blob/master/test/CsvImportTest/_files/test_resources_heritage.ods) too: see the [readme](https://github.com/Daniel-KM/Omeka-S-module-CSVImport).

**Comment by patrickmj** [comment]
@Daniel-KM Now that we're getting back into the swing of things after winter holidays, we can dive more into this. To keep things manageable, we're going to put a code/PR freeze for features for the time being. We'll be addressing bugs and any UI questions by creating new issues for them as we go along.

Thanks again for your contributions.

**Comment by Daniel-KM** [comment]
Ok. I'll publish the update for Folksonomy next week.

**Comment by mebrett** [comment]
In the advanced options - Action: are these things applied by row? (Create new, append, revise, update)?

**Comment by mebrett** [comment]
Also, is there a branch of mapping that currently works with this branch of import?

**Comment by patrickmj** [comment]
I haven't looked at it in a while, but I assume the danielkm-csv branch of mapping should work

**Comment by zerocrates** [comment]
I'm assuming this should be closed? @mebrett?
