### ISSUE TITLE
Function of Specific data for items

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#108]
One of the new options for item data mapping is "specific data for items" with the option to select a property and then "set item set". How is this meant to be used, and what format should the incoming data be in for it to work? 

![screen shot 2017-10-24 at 11 09 07 am](https://user-images.githubusercontent.com/2314070/31951390-fa207c98-b8ab-11e7-8b22-54647238b456.png)

**Comment by Daniel-KM** [comment]
You can attach multiple collections to an item. It may be the internal id, or any metadata of the existing item set. For example, if there is an item set with `dcterms:title` "My Title", you can use "My Title" as your identifier and choose it as property. The item will be included in it. it works as long as the properties are unique, so in general, this is the title, the `dcterms:identifier`, or the `internal id` (but for this one, you have to get it in your csv).

**Comment by Daniel-KM** [comment]
Another point: when there is a duplicate (for example two item sets with the same title and we choose the identifiers in "dcterms:title"), csv import will always use the smaller id (so the oldest resource). This is a good reason to have at least one unique identifier for all resources. Librarians and archivists generally have one, but not the other people.
