### ISSUE TITLE
Format for Visibility public/private

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#109]
Should the incoming data for this be boolean or text? does capitalization matter?

**Comment by Daniel-KM** [comment]
You can use anything, it will be true, except if you fill `0`, `false`, `off`, `private` (and `closed` for openess).

**Comment by mebrett** [comment]
So the default is public, for that option?

**Comment by Daniel-KM** [comment]
This is the default in Omeka Core when you create an item. If you don't set it, it will be public. But in the basic import settings, you can set it private by default.
