### ISSUE TITLE
Imported media becomes default

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#110]
When I manually add new media to an item, it appears below existing media in the sidebar, and the first-added item serves as the representative item for the thumbnail when browsing. However, using the CSV Import to add media does the opposite - the last item imported becomes the representative image, supplanting any existing media already attached, and the order in which media appear in the item's sidebar is reversed from usual (most recently added is at the top, not the bottom).

**Comment by Daniel-KM** [comment]
Fixed in #112.
