### ISSUE TITLE
module is using php-cli?

### ISSUE THREAD

**Issue by oupala** [omeka-s-modules/CSVImport#114]
It seems that this module is using php-cli to load CSV data.

On some hosters, it seems not possible to use php-cli:

```log
2018-02-01T08:14:28+00:00 ERR (3): Command "command -v 'php'" failed with status code 127.
2018-02-01T08:14:28+00:00 ERR (3): Omeka\Job\Exception\RuntimeException: PHP-CLI error: cannot determine path to PHP. in /srv/data/web/vhosts/htdocs/application/src/Job/DispatchStrategy/PhpCli.php:62
Stack trace:
[...]
```

Is there a way to bypass this limitation?

**Comment by Daniel-KM** [comment]
You may try to set its path directly in your `config/local.config.php`:

```php
    'cli' => [
        'execute_strategy' => 'exec',
        'phpcli_path' => null,
    ],
```

**Comment by oupala** [comment]
I added the following configuration:

```php
    'cli' => [
        'phpcli_path' => '/opt/php-7.1/bin/php',
    ],
```

and it seems to work. I now have some validation exceptions that I'll have to have a deeper look.

Thanks for the tip.

And by the way, what is the `execute_strategy` parameter for?

**Comment by zerocrates** [comment]
`execute_strategy` just switches between different methods for spawning a process. Different hosts sometimes require us to use a different PHP function to spawn a process in the background (in particular, when they've disabled one of the functions we'd otherwise use).

**Comment by oupala** [comment]
Is this parameter documented somewhere?

Is `exec` value the right value for me?

What are other possible values?

**Comment by zerocrates** [comment]
Documentation of the config parameters is something we need to work on.

Basically, it's something you'd change only if the default's not working. The default is `exec`, and the other option is `proc_open`. Both are simply the names of the PHP functions we use to execute a command. Usually the only reason you'd specifically pick one is that the other is blocked or there's some other server-specific issue. Generally, you shouldn't need to set that option.

**Comment by oupala** [comment]
Thanks for the tip. It worked for me.
