### ISSUE TITLE
No clear way to undo import

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#116]
ref #106 
I'm assuming the checkbox for past import is to undo them, but the boxes are not labeled and the button for the past imports tab simply says "submit".

If this is (still) the way to undo, there needs to be a label for the checkbox and the button should be clearly labeled with its function.

![screen shot 2018-03-06 at 11 23 58 am](https://user-images.githubusercontent.com/2314070/37044251-02856b6c-2131-11e8-8f4b-f651fb45de83.png)

**Comment by Daniel-KM** [comment]
Fixed. Note that only created resources can be removed, not the updated ones.
