### ISSUE TITLE
problem with automap with labels alone option

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-modules/CSVImport#118]
Ref #106 - When I am importing a CSV of items and check the box "automap with labels alone" the items imported have no metadata. Items are [untitled] and have no description, date, creator, etc. When I manually map to Omeka S data, the import works fine. This could be an issue with my CSV, but if that is the case, it would be helpful to have an error message pop up that says what exactly the issue is.

**Comment by Daniel-KM** [comment]
This should be fixed in the development version (https://github.com/omeka-s-modules/CSVImport/pull/105).
