### ISSUE TITLE
Restore button order

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#120]
ref #106 
In the currently released version of CSVImport, the buttons for mapping properties/etc go in the following order: Properties; Item Data; Media Import; (Map, if mapping active and applicable)

![screen shot 2018-03-06 at 4 12 52 pm](https://user-images.githubusercontent.com/2314070/37058721-6928283c-2159-11e8-9c94-be2b4e87fade.png)

But in the danielkm branch, they are in a different order, with Item/Resource Data before Properties. 
![screen shot 2018-03-06 at 4 12 22 pm](https://user-images.githubusercontent.com/2314070/37058823-b775c2ec-2159-11e8-9485-895606999f5a.png)

I would like to preserve the current order, for continuity in the UI.

**Comment by patrickmj** [comment]
A possible twist to this is is the way filters for the buttons get applied. It's possible that the filtered order will vary between installations. Something to check on.

**Comment by mebrett** [comment]
Is there a way to ensure that they stay in the same order regardless of installation? Otherwise it gets confusing for users.

**Comment by Daniel-KM** [comment]
This is fixed now with the last ui.
