### ISSUE TITLE
"Use multivalue separator" option appears repetitively in sidebars

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSVImport#121]
The "use multivalue separator appears in every mapping option sidebar, and as far as I can tell, it's the same option.

**Comment by zerocrates** [comment]
My recollection is that the idea is you can choose column by column whether each cell can contain multiple values.

**Comment by Daniel-KM** [comment]
Now, the multivalue separator works like the language field. See https://github.com/omeka-s-modules/CSVImport/commit/204d1d17eced99da78bcc742a91727c2e455076e.

**Comment by kimisgold** [comment]
Fixed in 7997df9ee46d9ff4c76f3468363ee5b27cf06bfe.
