### ISSUE TITLE
Set options appear in unidentified list below properties and item data

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSVImport#123]
Options such as using multivalue separators or language appear in their own list underneath the mappings, and it looks crammed into the mappings column. There's probably a better placement for them.

**Comment by Daniel-KM** [comment]
May be partially fixed in https://github.com/omeka-s-modules/CSVImport/commit/204d1d17eced99da78bcc742a91727c2e455076e.

**Comment by zerocrates** [comment]
Consensus seems to be that this was about the appearance of the set options in the mappings table and it was fixed by the addition of the "Options" column in that table.
