### ISSUE TITLE
"Set/unset the multivalue separator for all columns" should appear in mapping tab

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSVImport#124]
I dislike having to switch back and forth between the two tabs to see the effect take place. This also feels like a behavior that could follow the "batch actions" pattern: provide the option to apply an action to multiple columns (or all) at once using checkboxes.

**Comment by Daniel-KM** [comment]
Fixed in 86947a4 (can be improved).

**Comment by zerocrates** [comment]
Closed by merge of column-option-batch-edit branch.
