### ISSUE TITLE
"Advanced settings" should use the "expand/collapse" pattern

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSVImport#125]
The one-time click to expand button is an unexpected behavior with no way to undo.

**Comment by kimisgold** [comment]
Maybe there's no need to hide the advanced settings at all, but group them with the appropriate label.

**Comment by Daniel-KM** [comment]
I set a separate tab for it in my last commits, so there are Basic settings (in fact comment + resource settings), advanced settings (the process or what we want to do), and the mapping tab itself.
