### ISSUE TITLE
No unsaved changes warning

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#126]
Navigating away from an in-process import (after the file is loaded and you're on the mapping steps) does not trigger an "unsaved changes" message. I can move away to just about anywhere in the install and never get a message.

ref #106

**Comment by patrickmj** [comment]
I haven't been able to reproduce this. Does the warning appear for you in other modules or admin pages?

**Comment by mebrett** [comment]
It's working now, mostly.

What doesn't prompt an "unsaved changes" warning is if you're on the mapping page and have not yet clicked anything - no changes made, no mappings edited. Which means that what you lose is the file you've uploaded and any settings on that initial import page (resource type, auto map, etc)

**Comment by patrickmj** [comment]
Not sure there's much we can do about that, but I'm not too worried. I think it'd be odd to have a warning about unsaved changes on the page when there haven't actually been changes, and we're thinking through changes to redo the automap stuff anyway.

**Comment by mebrett** [comment]
Fair enough - something to put a warning about in the documentation.
