### ISSUE TITLE
Revise UI of Past Imports

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#127]
If nothing else, I feel like "parameters" could be reworded to just "Job 123" since that's what it links to and we don't use parameters anywhere else in the UI.

I could also see breaking out undos as their own line in the table, as we do in the currently available version of importer and most of the other importers in S, so that the Job can be its own column rather than a subset of action.

<img width="1030" alt="screen shot 2018-03-07 at 2 55 16 pm" src="https://user-images.githubusercontent.com/2314070/37115729-f49e8094-2219-11e8-8b29-b4596296d071.png">

**Comment by mebrett** [comment]
At present, undoing a job shows up in the Status column, rather than as a new import/job

<img width="1013" alt="screen shot 2018-03-07 at 3 13 20 pm" src="https://user-images.githubusercontent.com/2314070/37115776-190e0ae4-221a-11e8-8a28-6ebe7baad8fa.png">

**Comment by patrickmj** [comment]
I actually think the placement in the status column makes more sense than what we currently have. Especially if people use the Comment info to describe the action, it is a bit more concise, and reflects the user interaction better than the jobs, which are a bit opaque to real users.

**Comment by patrickmj** [comment]
I agree that a better word for "parameters" might be in order. Maybe something more human-friendly like "Import settings" or "Import options".  But "Job #" seems more unfriendly -- it's a term based more on the code than on people.

**Comment by zerocrates** [comment]
perhaps just "job details" which is accurate and maybe a little more approachable

**Comment by mebrett** [comment]
Job Details sounds good - it ties it in to the "jobs" tab on the left hand navigation, which is where you end up when you click the link.

**Comment by patrickmj** [comment]
Yeah, "Job details" has the virtue of helping people connect different parts of the interface.
