### ISSUE TITLE
Use case for "resources" import?

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#128]
What is the use case for an import with multiple resource types in a single sheet? Given that you cannot connect the resources you're importing (an item set and items for it) in a single sheet, when would someone want to import lots of different kinds of things without being able to relate them?

**Comment by mebrett** [comment]
@Daniel-KM - what were you thinking about when you added this option?

**Comment by Daniel-KM** [comment]
There is a very common usage: when you import books or student papers where each page are scanned. There are metadata for the book (author, publisher, date) and metadata for each page (number, ocr, transcription, type of page, etc.). When journals are imported, we don't want to import them one by one, but in one spreadsheet that contains the item and the media data. 

And the same spreadsheet is used too when the librarians share the data with the provider who makes the scans. And librarians don't want to create and store multiple spreadsheets.

It can be used too in any of the cases there are multiple media by item. For example, when your item describes a person, you may have multiple images or photos of him/her. Each item describes the person (who, dates, biography...), and each media is an image with specific metadata (photographer, painter, date, location, etc.). 

There are many cases where items and media are different. And this is an important quality of Omeka to distinct the item and the media properties.

**Comment by zerocrates** [comment]
:+1:
