### ISSUE TITLE
Resources import doubles media

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#129]
When importing a csv as resource, the final item - in this case media - keeps getting imported twice. 

This csv file:

```
this is what,dcterms:title,description,item identifier,item set id,creator,visibility status,date,media url,html media url
item set,Birbs,Lots of birbs,,,,public,,,
item,Barn Owl,The barn owl (Tyto alba) is the most widely distributed species of owl and one of the most widespread of all birds,,Birbs,,public,,,
media,Tyto alba,"A Barn Owl at British Wildlife Centre, Surrey, England.",Barn Owl,,snowmanradio,public,"23 July 2011, 16:03",https://upload.wikimedia.org/wikipedia/commons/c/c6/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg,
```

had this result:
<img width="1009" alt="screen shot 2018-03-15 at 2 23 16 pm" src="https://user-images.githubusercontent.com/2314070/37483556-9769ffd6-285c-11e8-9d95-5351e6126202.png">

**Comment by mebrett** [comment]
This happens on both danielkm and ui-improvements.

**Comment by kimisgold** [comment]
I tinkered with the CSV and was able to successfully import only 1 media item by adding a newline at the end. Could you try the import again with [this version of the file](https://cl.ly/361D323r0b3s/issue-129.csv)?

**Comment by mebrett** [comment]
Came through with only one of everything.

**Comment by zerocrates** [comment]
Does the problem with the original file happen _only_ when used as a "resources" import, or does it also happen if used as an "items" import?

**Comment by mebrett** [comment]
Importing as item (ignoring any of the resources mappings) works as expected - two items and one item with a media.

**Comment by Daniel-KM** [comment]
Probably fixed with https://github.com/omeka-s-modules/CSVImport/pull/105/commits/d064d9ab29c2aea8be5c5df1491136433dae8ddc too like #130 .

**Comment by zerocrates** [comment]
We can interpose our own iterator between the LimitIterator and the file... but I'd prefer not to do that if we can avoid it.

**Comment by zerocrates** [comment]
Turns out just to be a simple off-by-one error... if the underlying iterators were working properly this would probably have been invisible but this should prevent the weirdness from ever actually happening since we won't ever ask for offsets past the end of the file.
