### ISSUE TITLE
ui-improvement drawer stickiness

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#131]
The settings in the left hand drawer remain the same between CSV column choices. So if you're not paying attention and moving from properties to media, you can end up double-assigning something (see image, where I'd been doing visibility and moved on to media). 

<img width="485" alt="screen shot 2018-03-16 at 1 22 52 pm" src="https://user-images.githubusercontent.com/2314070/37536256-6a9e9eca-2920-11e8-8498-1770e74cf134.png">

It is possible to simply delete the extra mapping, so it's not an irreparable issue.

**Comment by mebrett** [comment]
On further testing, this only happens if both sections of the drawer are open when the user clicks apply changes. If you close/collapse the "resource data" section, it does not add any mappings (even if there was a mapping when you collapsed the section)

**Comment by kimisgold** [comment]
@mebrett The most recent commits (85ccc80f4184ce33543edefc2ad387ff0a187ed5, 99402c9d9d4f0c51b8a38b6b84613c122c124046) should fix your issues. Can you pull and test?

**Comment by mebrett** [comment]
Mapping drawer resets for each column header now. Thank you.
