### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#132]
It may be formatting in my CSV/ODS files, but I keep getting the following error on imports: `Fatal error: Unsupported operand types
in /websites/omekadev/home/www/mebrett/testomekas/modules/CSVImport/src/Job/Import.php on line 623` 

When this happens, it appears to stop the import - some of the lines will be imported but not all of them. 

I can share some of the file I've been uploading which have been throwing these errors if people want.

**Comment by mebrett** [comment]
Happening for the following csv on branch ui-improvements but not branch danielkm

`this is what,dcterms:title,description,item identifier,item set id,creator,visibility status,date,media url,html media url
item set,BirbsThree,Lots of birbs,,,,public,,,
item,Cooper's Hawk,"a medium-sized hawk native to the North American continent and found from Southern Canada to Northern Mexico. As in many birds of prey, the male is smaller than the female. ",,BirbsThree,,public,,,
media,Cooper's hawk in Toronto,"Cooper's Hawk -- backyard, Toronto, Canada -- 2004 November",Cooper's Hawk,,,public,2004,https://upload.wikimedia.org/wikipedia/commons/7/7b/Accipiter-cooperii-01.jpg,`

**Comment by patrickmj** [comment]
That doesn't look like something related to UI stuff, but .... maybe? The two different results are on the same installation/server, yes? I was hoping it might be a PHP version thing, but it sounds like not

**Comment by mebrett** [comment]
Exact same install, just different branches. It might be something about the mediawiki url's formatting, is all I can think. Curious to see what happens on other people's installs with either branch.

**Comment by patrickmj** [comment]
Could you upload the file itself? I'm not quite sure how to parse out the copy-pasted version above.

**Comment by zerocrates** [comment]
I edited the comment.

**Comment by kimisgold** [comment]
This should be fixed in in https://github.com/omeka-s-modules/CSVImport/commit/cabe301694728a3b7383b73e65cb75030e2ec0c0.
