### ISSUE TITLE
(re) add default values to mapping form

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#134]
Part of #133 , make sure that default values are present for all the mapping settings (or make some required?) to prevent confusing "Invalid Settings" message.

**Comment by zerocrates** [comment]
The offending setting appears to be "Resource identifier property"

It currently loads from saved user settings if it's been set before, but if it hasn't it starts blank and the form is invalid.

Minimal fix is probably just fixing/specifying the required attr for its input filter, to allow it to be blank. There's a slight complication also that this input (and the following one) actually have no effect on the default "mode" of "create."
