### ISSUE TITLE
A bit ambiguous what "Automap with labels only" does

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#136]
Leaving it unchecked, property headings like `dcterms:title` gets automapped. But, a column heading of `publisher` is not. Checking the box, though, puts the mapping in.

I lean toward making the module effectively work as if "Automap with labels only" is always on, and people can opt out on the next screen. That'd remove the checkbox and have everything available filled in.

Thoughts, @zerocrates and @Daniel-KM?

**Comment by Daniel-KM** [comment]
It is used for people who don't want to modify their original spreadsheets with standard headers (title, publisher), so it try to determinate the terms from the header. 

Many issues have been found (even if they work in my installs), so I'm going to fix them in May (if not done before).

**Comment by Daniel-KM** [comment]
If some features should be removed, this is not a problem, as long as they can be triggered by any mechanism.

**Comment by mebrett** [comment]
Restore the box (so that people can opt out) but leave it on by default.
