### ISSUE TITLE
New property mappings not appearing

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#137]
On latest of ui-improvements, property mappings are no longer happening: clicking a property doesn't make it show up in the mappings column.

Could be related to the things I've been removing on that branch, but when I backed up to commits before I started that, same thing. So, I'll probably need to consult with @kimisgold to figure out what's up.

**Comment by kimisgold** [comment]
@patrickmj Are they showing up in the mapping column after you click "Apply changes"? I wanted to keep UI behaviors consistent in that the user configures all the mappings they'd like in the sidebar, and then they all apply after hitting the "Apply changes" buttons.

**Comment by patrickmj** [comment]
Ah. Yes, they do appear after I hit "Apply changes". I think it'd be helpful to have some kind of visual effect when clicking a property. Maybe something that draws attention to the "Apply changes" button after making a change? It's a little confusing to see no response to clicking on a property if you don't know that a change only happens after clicking the button down at the bottom. A change to the style of the "Apply changes" button when there is a change in progress might do the trick? Or some style change to the property button to signal that it's in play, but I'd aim for highlighting what the next action should be.

**Comment by patrickmj** [comment]
What's the expected behaviour if someone makes a change, hits Apply, then makes another change and hits Apply again (including both adding and removing mappings?)

**Comment by kimisgold** [comment]
On second application...

1) ... if they add new properties, the new properties are added.
2) ... if they add already added properties, those properties remain applied.

You can only remove properties by marking them for removal with the trash can icon.

**Comment by patrickmj** [comment]
That makes sense. Any thoughts about the thing above about signalling changes?

**Comment by kimisgold** [comment]
There is a gray highlight when you click on a property. Does that appear for you?

**Comment by patrickmj** [comment]
That does appear for me in both FF and Chrome. I'm still not sure that I see what's happening for next steps, though.

**Comment by kimisgold** [comment]
Hmm, so here are questions to help with my understanding: are next steps unclear for instances where you are mapping resource data or media sources? How do you feel about those workflows compared to mapping properties?
