### ISSUE TITLE
Multivalue option not recognized

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/CSVImport#143]
Using the [example file](https://github.com/Daniel-KM/Omeka-S-module-CSVImport/blob/master/test/CsvImportTest/_files/test_resources_heritage.ods) and importing mixed resources, I get the following error in my log:

```
2018-09-04T20:03:57+00:00 ERR (3): "Architectural Heritage | Famous People" (dcterms:title) is not a valid item set.
```

**Comment by zerocrates** [comment]
This is the "all columns multivalue" option, or marking a specific column as multivalue on the mapping screen?

I know about the all columns not working... even though it's a switch on Basic Settings, it appears it's actually supposed to work just through JS that sets the Multivalue option on every column.

**Comment by zerocrates** [comment]
Related to #124
