### ISSUE TITLE
"Skip row" action purpose?

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#148]
The "Action" dropdown under advanced mostly is pretty easy to understand: it changes what the importer does for every row: create, delete, and several types of update.

What purpose does "Skip row" serve? The action determines what to do for _all_ rows, so setting to Skip row is basically saying "Do nothing" as far as I can tell.

**Comment by Daniel-KM** [comment]
It is to skip the row, so it imports nothing...
Mainly for testing purpose, it can be removed.

**Comment by zerocrates** [comment]
Thanks.
