### ISSUE TITLE
Purpose of "Internal ID" "Data" option?

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#149]
The set of choices for "Data" or "Generic Data" are:

- Internal ID
- Resource template name
- Resource class term
- Owner email address
- Visibility public/private

The last 4 are all easy: they're pieces of data that apply to any Resource, and mapping a column to them will override the defaults for those values from the settings.

Internal ID I don't get, though. Other places it's used, I believe "Internal ID" simply refers to the Omeka S `o:id` for the resource, so you can use it to look up existing resources in the system, for use in the non-create Action modes, or when linking Items to Sets or Media to Items. Those all make sense.

_This_ usage of it though, sets a flag `column-resource`... so I guess this choice is actually setting the column that the "Resource identifier property" advanced setting is used with? (In other words, the contents of a column mapped with this choice are used to look up the resource to act on for the row.) If so, the name Internal ID here really doesn't make any sense.

**Comment by Daniel-KM** [comment]
"Resource identifier" and "internal id" haven't the same meaning. Internal id is the o:id, but resource identifier is the identifier that the user chooses from the metadata, generally the dcterms identifier or sometime the title, but it can be the internal id too (rarely used). So it should be renamed.

**Comment by zerocrates** [comment]
Okay thanks, that's in line with what I was thinking.

The other usages of "Internal ID," the ones where they come at the beginning of a select that lists other properties as the rest of the choices, those are fine. It's just this one in the "data" area that needs to change.

You can also only meaningfully have _one_ column mapped this way, correct? Anything else is at best confusing. I almost want to move it from a mapping to a dropdown of columns to pick from in the Advanced tab, just so all the Action-related stuff is together...

But at least for now I'll change that option label.

**Comment by Daniel-KM** [comment]
Yes, it's simpler.
