### ISSUE TITLE
Unknown column 'added_count' in 'field list'

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/CSVImport#153]
After upgrading to Omeka S 1.2.0, CSVImport does not work anymore. Jobs are in the "error" state with the following log:

`Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'added_count' in 'field list' in /mywebsite/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107`

If I tried to upgrade to the last (git clone) version of CSVImport, I have a blank screen for each page. The same if I use the [CSVImport fork of Daniel KM](https://github.com/Daniel-KM/Omeka-S-module-CSVImport/)

**Comment by zerocrates** [comment]
This is with what version of CSV Import that you were getting that error? Version 1.1.0 is still the latest release and I don't think it would be giving you that error.

**Comment by pprw** [comment]
It is the 1.1.0 which generates the error. More recent (git) versions have the side effect to prevent the website to be displayed (blank page for every page) when installed.

**Comment by zerocrates** [comment]
Are you sure you were using 1.1.0 before?

CSV Import 1.1.0 _has_ an "added_count" column, and the later, in-development versions don't. Maybe you upgraded to a newer version at some point? Upgrading would have dropped that column. Once you've upgraded, you can't simply go back.

It might be simplest to switch back to the newer version you tried and uninstall it. Then you could reinstall version 1.1.0 (or some other version, if you prefer).

**Comment by pprw** [comment]
I think the installation of newer versions than 1.1.0 does not work because the added_count" column already exist. And uninstalling version 1.1.0 of CSVImport does not clean the added_count" column.

Can I remove directly the added_count" column from the mysql database?

**Comment by zerocrates** [comment]
Where are you getting 1.1.3 from? The develop branch here is only 1.1.1.

Anyway, you can completely remove/drop the CSV Import tables from the database. You'd also have to remove the CSVImport row from the `modules` table if you're going to "manually" uninstall like that.

**Comment by pprw** [comment]
Maybe the 1.1.3 was from the fork of Daniel KM.

Anyway, I drop the tables `csvimport_entity`, `csvimport_import` and the row `CSVImport` from the modules table.

Now I have CSVImport 1.1.0 working again.
