### ISSUE TITLE
Testing Feedback on Interface

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/CSVImport#154]
@zerocrates @mebrett 

I ran a couple of imports that included data mappings through existing Omeka S resource IDs, but not any multiple mappings. I did not read the documentation first. In fact, I'm not sure if there is documentation.

In my first experience with the mapping tab of the process, I mistook the mapping-plus icon for the configure-wrench, because I thought I was adding, hence the plus, specifications for the mapping. I then tried to use the "Generic Data" options to select the data type -- in this case Resource Identifier -- for the cells. Once I figured out that I just needed the much more minimal options offered by the configure-wrench, things were easier. 

I wonder if we can come up with a better header for the plus slider drawer than "Add mapping" that specifies how that mapping is different than telling the system how to use the column data. 

Since the configuration options are simpler and far more likely to be used regularly, maybe we UI should list the configure-wrench first and mapping-plus second in the row.

Also, I noticed that there is some inconsistency of UI language between the plus mappings and the wrench -- Plus calls the Generic Data Type "Resource identifier" and the Wrench Data Type says "Import as Omeka S resource ID." If they are the same, perhaps they should both specify "Omeka S resource ID"

**Comment by zerocrates** [comment]
"Resource identifier" in Generic data is not the same as "import as Omeka S resource ID"... the generic data one is only used with the "Action" stuff in Advanced Settings.

We had/have a plan to basically move that out of Generic and over into Advanced as well, but there's some annoyances with rendering a column picker in the form in that particular area.

**Comment by sharonmleon** [comment]
Okay then. Well, the terms were close enough that it compounded my confusion about whether I was in the right place to do the mapping.

**Comment by sharonmleon** [comment]
And, because I was used to the old CSVImport, I was definitely automapping. I guess most people don't?

**Comment by mebrett** [comment]
We should definitely tweak the language of resource id vs. import as Omeka S id.

My sense with automapping is that people who are used to vocabularies or have a lot of sheets to bring in may use it, but that there will be a fair number of people who don't start tidying up their old spreadsheets until CSV import has thrown an error or two for bad data.
