### ISSUE TITLE
Map values to non-native data types

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CSVImport#156]
Currently we can only map values to the native data types: literal, uri, and resource. This is because we don't have prior knowledge of how to structure the value objects of non-native data types. Maybe we could add an event so other modules can register data types and build the value objects during import.

**Comment by zerocrates** [comment]
On branch `data-types`:

Modules should be able to add to the list of types by specifying an array in module config under `[csv_import][data_types]`

Structure is

```
'csv_import' =>[
    'data_types' => [
        'type id' => [
            'label' => 'Human label for dropdown',
            'adapter' => '"type of type" (i.e., treat this type as one of: literal, uri, or resource)',
        ],
    ],
],
```

**Comment by zerocrates** [comment]
Currently this only allows you to say your type should be treated as equivalent to one of literal, uri, or resource for purposes of building the input JSON... arbitrary JSON building would have added a somewhat significant level of complexity and to my knowledge we don't really currently have types that fall outside those buckets, really.

**Comment by zerocrates** [comment]
This is merged so it's just a matter of having support on the module sides and having releases of this and the appropriate modules.
