### ISSUE TITLE
Documentation for new features

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#164]
- Pluggable data type support: Modules that add data types can have those types selectable in the Options data type dropdown. Example: current master of NumericDataTypes
- URI label support: When mapping a column as URI (with the URI data type option), you can set the label as well as the URL by including it after a space: `http://example.com This Is The Label`. Everything after the first space should be treated as the label. This should also work correctly in "multivalue" columns
- Resource data dropdown removed and replaced by separate sections: this will affect screenshots and some examples of where things are placed: the biggest change is to mixed resource imports, where the Resource data section and dropdown are gone and there are just accordions for Item, Item set, and Media-specific data. In specific-type imports, the name of the "Resource data" section is changed accordingly also (an Item import will show "Item-specific data" as a section rather than "Resource data")
- Private value mapping option: Added to the "options" sidebar, this means all Property values mapped from this column will be imported as private (note this is about making specific values private, not the whole resource)

**Comment by zerocrates** [comment]
This is all just on the develop branch

**Comment by mebrett** [comment]
I think I managed to get everything: https://github.com/omeka/omeka-s-enduser/blob/csvimport2-1/docs/modules/csvimport.md

**Comment by mebrett** [comment]
Just a note that the "private" option shows up for user imports, which seems a bit odd.
