### ISSUE TITLE
White screen of death upon installing module

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#165]
I updated a bunch of stuff on my local installation, and when I tried installing CSV Import I got white screen of death. Nothing in the logs, and I've checked that in .htaccess my application environment is set to develop. I'm pretty sure all repos are on master, so this seems quirky. Any guidance on things that I should double check?

Thanks

Here's system info:

```

Omeka S
--
1.4.0

7.2.19-0ubuntu0.18.04.1
apache2handler
128M
8M
5M
Yes
apache2handler, calendar, Core, ctype, curl, date,  dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, json,  libxml, mbstring, mysqli, mysqlnd, openssl, pcre, PDO, pdo_mysql, Phar,  posix, readline, Reflection, session, shmop, SimpleXML, sockets, sodium,  SPL, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml,  xmlreader, xmlrpc, xmlwriter, xsl, Zend OPcache, zip, zlib
, pcntl_alarm, pcntl_async_signals, pcntl_exec,  pcntl_fork, pcntl_getpriority, pcntl_get_last_error, pcntl_setpriority,  pcntl_signal, pcntl_signal_dispatch, pcntl_signal_get_handler,  pcntl_sigprocmask, pcntl_sigtimedwait, pcntl_sigwaitinfo,  pcntl_strerror, pcntl_wait, pcntl_waitpid, pcntl_wexitstatus,  pcntl_wifcontinued, pcntl_wifexited, pcntl_wifsignaled,  pcntl_wifstopped, pcntl_wstopsig, pcntl_wtermsig

5.7.26-0ubuntu0.18.04.1
mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES,  NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO,  NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

Linux 4.15.0-54-generic x86_64



```

**Comment by patrickmj** [comment]
Addtional: CSVImport version 2.0.0, master branch

**Comment by zerocrates** [comment]
The likely issue here is that, when you're using it from a Git checkout, you need to install a dependency with Composer (run `composer install` in the CSVImport directory).

Installs from the zip have the dependency pre-included.

**Comment by patrickmj** [comment]
Ah. Makes sense. I expect giving that a whirl will fix things.

I look forward to the day that I can claim build dependencies on my tax return.
