### ISSUE TITLE
Per column setting "Language" doesn't work

### ISSUE THREAD

**Issue by psalido** [omeka-s-modules/CSVImport#166]
At "Column Option", "Language" settings doesn't work. Problem is at CSVImport\src\Mapping\PropertyMapping.php: 

Setting by colum is on variable $languageMap, but after is referenced with uninitialized var $languageSettings. 

Renaming languageSettings to languageMap solve this issue.

**Comment by zerocrates** [comment]
Thanks for the report. This will be fixed in the next release.
