### ISSUE TITLE
New CSV Import breaks on Omeka S 2

### ISSUE THREAD

**Issue by brimwats** [omeka-s-modules/CSVImport#168]
I downloaded the zip from github. Unpacked it and then changed the name. When I click install the website times out and then goes white, and there is no way around this except to go into filezilla,  delete CSVImport, and then go into PHPMyAdmin from cpanel and then delete all CSVImporter records from the database (otherwise I get errors like "files missing but recorded in database!"

I've repeated these steps 3-4 times now, the first time I accidentally did it with the -develop branch as that's the one that links out from https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html

**Comment by zerocrates** [comment]
You said you unpacked the zip and change the name... you shouldn't need to do this with a packaged Omeka S module: they're zipped up so that they extract into the properly-named folder.

What specific link did you click on to download the zip file?

**Comment by brimwats** [comment]
When I click here:
https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html

It takes me here
https://github.com/omeka-s-modules/CSVImport

when I download, it downloads 
CSVImport-develop.zip

When I go to the other active branch
https://github.com/omeka-s-modules/CSVImport/tree/master

it gives me
CSVImport-master.zip

All the other new modules downloaded this way (from ...-master.zip) work fine. I have downloaded HideProperties Mapping MetadataBrowse ValueSuggest ZoteroImport and installed without issue.

**Comment by zerocrates** [comment]
My general suggestion would be that you download modules from the [Omeka.org modules directory](https://omeka.org/s/modules/), which will point you at the correct download link for each module.

If you prefer to use GitHub, that's fine too, and my suggestion there would be to use the Releases section. If you look at the [recent release of CSVImport](https://github.com/omeka-s-modules/CSVImport/releases/tag/v2.1.0), the first thing under Assets (CSVImport-2.1.0.zip) is the download link I'd suggest; this is the same one as linked from omeka.org.

The difference is usually pretty minor for most modules: just a matter of the folder having the proper name by default or not, and perhaps some unnecessary development-only files excluded. CSV Import is a little different, as it's one of the few modules that has dependencies installed with Composer. You can use Composer to install these if you're using Git to check out or develop on the module, but in the prepackaged zip file we pre-install them so users can just drag and drop.

This wrinkle with this module is mentioned on the readme, under "Installation."

**Comment by brimwats** [comment]
Hi @zerocrates! Thank you for the clarification. You're absolutely right, and I was being careless. I can confirm that it works now. :)
