### ISSUE TITLE
Error when loading module: invalid config/module.ini file

### ISSUE THREAD

**Issue by ekaune** [omeka-s-modules/CSVImport#169]
Hi, I've been pulling my hair out for an hour or so trying to load this module, but no matter what I do, I always get this error on the modules page: invalid config/module.ini file. I'm using Omeka S version 2.0.2 and CSVImport 2.1.0.

Thanks!

**Comment by zerocrates** [comment]
How are you downloading/installing the module? From [the Omeka.org modules page](https://omeka.org/s/modules/CSVImport/)? Or somewhere else?

**Comment by ekaune** [comment]
Yeah, that's where I got it.

**Comment by ekaune** [comment]
As far as installing it goes, I'm using FileZilla to move it over to my Reclaim Hosting site.

**Comment by zerocrates** [comment]
Maybe you're having an issue with permissions? Like the server (and therefore Omeka S) can't read the files you're uploading?

Reclaim may be able to take a look. Have you asked them?

**Comment by ekaune** [comment]
I can certainly ask them. I haven't had trouble with other modules, though.
