### ISSUE TITLE
First linebreak in multiline cell gets eliminated

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#178]
The issue seems to come from the usage of the DROP_NEW_LINE flag to SplFileObject. 

I think we can just take this out without losing anything: it seems it was intended to be part of skipping empty lines in the input but as far as I can tell it's not actually required for that purpose. We'll want to do some testing on this, of course.

**Comment by zerocrates** [comment]
This is a longstanding PHP bug: https://bugs.php.net/bug.php?id=69181

But if we don't need the flag in the first place we can just sidestep it.

**Comment by zerocrates** [comment]
Removing the flag doesn't affect the dropping of empty CSV rows, they're still skipped as expected.

What it does change is the treatment of totally blank lines, lines with no CSV delimiters at all on them. They now raise our "wrong number of columns" error.

I'm tempted to say this is OK: those truly-blank lines should only be arising from an incorrectly done handmade or hand-edited CSV, so I'm not sure we need to worry about supporting them,

**Comment by oupala** [comment]
Issue is now fixed in release 2.1.2 of the CSVImport module.
