### ISSUE TITLE
Silent automap error with UTF-8 + BOM file

### ISSUE THREAD

**Issue by triplingual** [omeka-s-modules/CSVImport#180]
Excel for Mac saves UTF-8 to CSV with a byte order mark.
Using a CSV thus saved means the BOM will result in CSV Import's automapping feature failing for the first column, though it succeeds for other automappable columns.
One workaround is to map the first column manually, but it would be nice to not have to do this.
Another workaround is to open the saved CSV in a text editor and re-save without the BOM, but it would be nice to not have to do that either.

Omeka S 2.1.2
CSV Import 2.1.1

(Excel's doing it wrong, in my POV, but that's what most of our users are going to have experience with.)

**Comment by zerocrates** [comment]
I don't have ready access to Excel for Mac, can you share a simple example CSV? (I could just make a CSV and insert a BOM at the beginning but I'd like to test/confirm against something "real"-ish)

We should be able to just trim `\xEF\xBB\xBF` from the first column heading (or from the file as a whole before processing it, though just trimming on the column is possibly simpler).

**Comment by triplingual** [comment]
I'll give you what we are using for a ~template for our curators (2 records), so it's real and not: https://yale.box.com/s/4gb31oicqj56l6z4roxif549j2bjwz2u (GitHub won't let me drop in the actual file)

**Comment by triplingual** [comment]
🕺🏻
