### ISSUE TITLE
Title not imported when importing medias

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/CSVImport#183]
There is a bug in CSVImport which prevents to import the title of the media.

I selected "media" as import type:

![image](https://user-images.githubusercontent.com/5262986/98093514-55467b00-1e88-11eb-8c8b-539a3280199e.png)

I did the mapping where 
- ID refers to Omeka ID of items already imported.
- there is a (DC) title and a (DC) date for each media imported
- the html fragment is inside the "Content"

![image](https://user-images.githubusercontent.com/5262986/98093609-7018ef80-1e88-11eb-9978-07a220895743.png)

After the importation, I have all the new medias but  no title for them (instead it is a not-interpreted html which is used as title).

list of media:

![image](https://user-images.githubusercontent.com/5262986/98093447-42cc4180-1e88-11eb-8b95-221a6ffc3135.png)

Inside an item:
![image](https://user-images.githubusercontent.com/5262986/98094859-203b2800-1e8a-11eb-9c4f-0c1cea92cbd3.png)

**Comment by pprw** [comment]
A possible workaround is to select  "mixed resources" as import type and to add a column containing "media" in the csv.

This way, media's titles are imported correctly.

**Comment by zerocrates** [comment]
It should definitely be letting you import a title in this situation... I'll see if I can reproduce the issue.

**Comment by zerocrates** [comment]
OK, I've reproduced the issue.

I believe I have a fix; it's code that specifically only deals with the ingest of HTML-type media. Can you confirm it's just HTML media where you're seeing this issue?

**Comment by zerocrates** [comment]
This issue is now marked as closed because of my commit, but please do comment on whether this addresses your problem.

**Comment by zerocrates** [comment]
I also made a [quasi-related commit](fa8bc728e87032d9a67dd3058483f33a8a9f0fad) that will stop the importer from using the HTML content as the default title when none is mapped.

**Comment by pprw** [comment]
>  it's just HTML media where you're seeing this issue?

Yes indeed.

> I also made a quasi-related commit that will stop the importer from using the HTML content as the default title when none is mapped.

Wonderful. Thanks!
