### ISSUE TITLE
Integrity constraint violation whenever updating items with resource template

### ISSUE THREAD

**Issue by cfeh** [omeka-s-modules/CSVImport#184]
Whenever I update items that have a resource template set (even just "Base Resource"), I get an error message about some integrity constraint violation (see below). When I unset the resource template before the import, it works again without error message.

(I'm using CSV Import version 2.2.1 on Omeka 3.0.1; I used BulkImport on Omeka 2 without this problem, but that module still can't even be installed in Omeka 3).

---

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'UNIQ_4689E2F116131EA549213EC' in /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#3 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(400): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(411): Doctrine\ORM\EntityManager->flush()
#7 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#8 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(1183): Omeka\Api\Manager->update('csvimport_impor...', 3, Array)
#10 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(203): CSVImport\Job\Import->endJob()
#11 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
#12 /var/www/vhosts/ici-berlin.org/omeka-s/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#13 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/Dispatcher.php(91): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
#14 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Controller/IndexController.php(154): Omeka\Job\Dispatcher->dispatch('CSVImport\\Job\\I...', Array)
#15 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): CSVImport\Controller\IndexController->mapAction()
#16 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#18 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#19 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#20 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#21 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#22 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#23 /var/www/vhosts/ici-berlin.org/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#24 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'UNIQ_4689E2F116131EA549213EC' in /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
Stack trace:
#0 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#1 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#2 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#3 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(400): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(411): Doctrine\ORM\EntityManager->flush()
#6 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#7 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(1183): Omeka\Api\Manager->update('csvimport_impor...', 3, Array)
#9 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(203): CSVImport\Job\Import->endJob()
#10 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
#11 /var/www/vhosts/ici-berlin.org/omeka-s/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#12 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/Dispatcher.php(91): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
#13 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Controller/IndexController.php(154): Omeka\Job\Dispatcher->dispatch('CSVImport\\Job\\I...', Array)
#14 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): CSVImport\Controller\IndexController->mapAction()
#15 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#16 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#17 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#18 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#19 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#20 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#21 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#22 /var/www/vhosts/ici-berlin.org/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#23 {main}

Next Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO resource_template_property (alternate_label, alternate_comment, position, data_type, is_required, is_private, resource_template_id, property_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, 1, "[]", 0, 0, 1, 1]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'UNIQ_4689E2F116131EA549213EC' in /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:55
Stack trace:
#0 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(162): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO res...', Array)
#3 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#4 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#5 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(400): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(411): Doctrine\ORM\EntityManager->flush()
#8 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#9 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(1183): Omeka\Api\Manager->update('csvimport_impor...', 3, Array)
#11 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Job/Import.php(203): CSVImport\Job\Import->endJob()
#12 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
#13 /var/www/vhosts/ici-berlin.org/omeka-s/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#14 /var/www/vhosts/ici-berlin.org/omeka-s/application/src/Job/Dispatcher.php(91): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
#15 /var/www/vhosts/ici-berlin.org/omeka-s/modules/CSVImport/src/Controller/IndexController.php(154): Omeka\Job\Dispatcher->dispatch('CSVImport\\Job\\I...', Array)
#16 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): CSVImport\Controller\IndexController->mapAction()
#17 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#19 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#20 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#21 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#22 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#23 /var/www/vhosts/ici-berlin.org/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#24 /var/www/vhosts/ici-berlin.org/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#25 {main}

**Comment by zerocrates** [comment]
I wasn't able to reproduce this issue.

I notice a couple of odd things about your error message:

First, it's a strange error to begin with: the error is about updating a template, not updating an item, which is odd because the CSV Import doesn't edit templates at all. 

Second, it looks like this error is actually happening at the very end of the import process, when just saving data like the completed date and the number of records added and updated. Do the changes from your import actually happen and get saved, or not?

Third, I think from the log here you're using the Synchronous job strategy. Do you not have the ability to run background jobs on your server? It's fairly rare for users to use the CSV Import synchronously. It's possible this is related to the issue.

**Comment by cfeh** [comment]
Thank you for the quick response! 
I don't about your first point, but concerning 2: the import indeed seems to work, but I felt uncomfortable with error messages accumulating. 
Point 3: I don't remember why I added the synchronous strategy at some point to local.config. When I comment it out, no error appears. So I guess that was it! 
Thanks again!
