### ISSUE TITLE
Undo checkboxes only selectable for create action jobs?

### ISSUE THREAD

**Issue by joebauer** [omeka-s-modules/CSVImport#185]
Hi! We're seeing that the undo checkboxes in the "past imports" interface are only selectable for jobs that are of the "create" action type. Is this intentional? We would like to be able to also roll back update, revise, and replace jobs, too. Thanks!

![image](https://user-images.githubusercontent.com/6989685/110480709-cb682200-80b4-11eb-84af-eaebe11a9a0b.png)

**Comment by zerocrates** [comment]
You can't Undo update jobs because the previous state of the items isn't stored: Undoing a "create" import job is just a matter of deleting the resources that were created, but undoing an update requires rolling back to a prior "version," essentially, which the importer can't do.
