### ISSUE TITLE
Importing labels along with URIs using CSVimport

### ISSUE THREAD

**Issue by remyienco** [omeka-s-modules/CSVImport#187]
Hello,
I am trying to import datas with the property "uri" from BiBo : I need the CSVImport module to select the URI _and_ to add the desired label onto it.
![Opera Instantané_2021-04-13_165659_localhost](https://user-images.githubusercontent.com/71893470/114574237-5d95b400-9c79-11eb-9028-5cb108ce7e00.png)
On this screencap, I manually added the label I want to appear : IG etc. Except I do have about 800 items to edit this way : how can I automate it with the module ? How do I edit the CSV file and do the mapping ? If not yet, is there a way to make it happening ?
Thanks & regards,
Rémy

**Comment by zerocrates** [comment]
If you leave a space after the URL and put the label after that, in the same cell, CSV Import will pick up the label.

So `http://example.com Label goes here` would be what should be in the cell.

**Comment by remyienco** [comment]
> If you leave a space after the URL and put the label after that, in the same cell, CSV Import will pick up the label.
> 
> So `http://example.com Label goes here` would be what should be in the cell.

It works, thank you very much !
