### ISSUE TITLE
CSV file detection fails (with possible the solution)

### ISSUE THREAD

**Issue by andrisi** [omeka-s-modules/CSVImport#192]
CSVs not detected for me, probably either because uploaded with Chrome or because I'm using nginx. It's clear that the reason for this is that the IndexController::getSource() function does not handle the case where the $mediaType is 'application/csv' which I do get when I upload a .csv file. Thanks.

**Comment by zerocrates** [comment]
It's probably neither Chrome nor nginx, but certain versions of the `file` library on servers incorrectly reported the type for CSVs as "application/csv" (the type is "text/csv").

We actually already have a change committed to address this: https://github.com/omeka-s-modules/CSVImport/commit/39900aebf5854406c7790849488e7ae2e1475316

We'll work on getting a release out that includes this change.

**Comment by zerocrates** [comment]
This fix came out with v2.3.0.
