### ISSUE TITLE
Test site assignment

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#193]
Test on latest develop of the module.

The Sites dropdown is under Basic Settings, and is a "chosen"-enhanced multi-select. The same sites your user would have preselected when adding an item should also be preselected here, this includes the "auto-assign all new items" sites and any user-selected default sites. Users should be able to add to or remove from this default selection.

Previous behavior was to always add all items only to the "auto-assign" sites and present no UI for modification.

The selection should be present and functional for both Item and Mixed resource imports, but no other types.

Performing an update rather than an import will also apply the selected sites: this is a change from prior behavior as we previously did not set sites at all. To leave site assignments alone all sites must be deselected in Basic Settings.

**Comment by sharonmleon** [comment]
When importing new items, all of my sites are appearing in the selection box, even though none of them has the auto-add new items setting checked, and my users has auto-add for only one of them.

**Comment by sharonmleon** [comment]
Have tested everything except update, and all seems good.
