### ISSUE TITLE
Mapping for Item Sets Tree module

### ISSUE THREAD

**Issue by futurelessvivid** [omeka-s-modules/CSVImport#195]
I first left a comment with the creators of the Item Sets Tree module, but someone there suggested I make a suggestion here.

Is it possible to add a mapping for CSV Import so that when adding multiple item sets in a bulk fashion, one could set each to a particular parent Item Set in collaboration with Item Sets Tree module? I did a bulk addition of a large batch of Item Sets. It would be helpful not to have to individually set each in the edit feature with each Item Set.

**Comment by zerocrates** [comment]
I believe we made a suggestion to this effect at the time on the ItemSetsTree issue for this, but to clarify here: in general this module doesn't support other modules itself, instead it allows them to add their own options for mapping their data. So I think this feature would be done in the ItemSetsTree module.
