### ISSUE TITLE
Add user manual link & help text

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/CSVImport#205]
Could we modify the CSV Import interface a bit? It would be good to have a link to the docs here (on "see the documentation"):
![hyperlink](https://user-images.githubusercontent.com/28012148/204874492-5e287fd2-6858-47a4-ab3a-d3c4874ed90c.PNG)

And ideally more help text right in the interface. Maybe selecting one of the options from the dropdown gives a one-sentence explanation.

**Comment by zerocrates** [comment]
Link is in.

As for more text... simplest option is to have a parenthetical right on each choice that says what it does, I'd think.

**Comment by allanaaa** [comment]
Okay, this is more or less what the manual says:

>     Create a new resource (Each row in the CSV will become a new resource)
>     Append data to the resource (Add new data to the resource, based on an identifier for an existing resource)
>     Revise data of the resource (Replace existing data of the resource with data from the CSV, except if the corresponding cell in the CSV is empty)
>     Update data of the resource (Replace existing data of the resource with data from the CSV, even when the corresponding cell in the CSV is empty)
>     Replace all data of the resource (Remove all properties of the resource, and fill with new information from the CSV)
>     Delete the resource (Delete all resources matched by the identifier)
