### ISSUE TITLE
Run through CSVImporter

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#21]
CSV Importer is ready to have a look. Master branch of CSVImport, and latest develop branch for Omeka S.

CSV file(s) should have a lot of different columns, including:
* multiple values with a separator
* all the allowed media types, except upload
* some headers that are automapped to property names (go to vocabularies and click on the list of properties for examples)
* item set ids
* owner email addresses
* resource class term (from the Classes lists on the vocabularies page)
* resource template names

On the import page, choose the csv file, hit next. Try all the different mapping options and combinations you can think of. The 'Basis Import Settings' should apply to all the items imported, unless they are overridden / added to in the mapping options.

In the mapping options, the 'URL' checkbox means that the data type for the values will be a URL, and the 'multiple values' checkbox means that there are multiple values, separated by whatever you put in the CSV file and set in the basic settings.

Click the buttons for the different types of mappings available -- metadata, media, or item data (like the owner email or item set id). Sidebars for each type will let you pick what kind of mapping to use for each column.

Lots of variations to look at, so a couple different CSV files might be good.

I'll also be curious about how it handles CSV files that are broken in different ways. Separate new issues for each thing that comes up will probably be much more manageable than comments here.

Let me know what questions come up.

Thanks

**Comment by mebrett** [comment]
Things that are working fine and so don't need an issue: multi-value imports, mapping resource template, mapping Item Set, mapping multiple types of media (each with tis own columns),
