### ISSUE TITLE
Testing for CSV Import 2.5.0

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#210]
Test on develop branch, version should be 2.5.0

This version has new Composer dependencies, so a github update will need a run of `gulp deps:module` to install/update them. I can make a updated zip package if that's more convenient also.

Really this is just a "confirm non-broken" kind of testing rather than looking at new features.... in particular the library that handles ODS Open/LibreOffice spreadsheets was changed out and so that should definitely get a look. "Media" type imports should also get a look, there's a fix in here for how media added through those imports gets ordered within their parent item (at the end, and correctly ordered with respect to other media added in the same import to the same item). Other fixes are mostly some cosmetic stuff in the forms, plus PHP version-related deprecation messages and things like that, which shouldn't really need any specific testing.

**Comment by zerocrates** [comment]
I don't think this requires any documentation changes... there might be some slight screenshot differences but probably nothing rising to the level of needing a replacement.

**Comment by allanaaa** [comment]
With Mapping and Extract Metadata turned off, the media append worked fine. 

I hadn't realized that uploading media won't just append and append new files forever, there's some kind of redundancy checking going on. Is that at a hash level on the file itself, or something simpler like the filesize or the upload URL?

**Comment by zerocrates** [comment]
From my reading of the threads involved I think just that Mapping issue hasn't been fixed yet and is still present?

**Comment by zerocrates** [comment]
> I hadn't realized that uploading media won't just append and append new files forever, there's some kind of redundancy checking going on. Is that at a hash level on the file itself, or something simpler like the filesize or the upload URL?

There's a check in CSV Import for... I believe it's the o:source, so a file with an exactly matching preexisting filename/URL will be considered "duplicate" and not added again.

**Comment by allanaaa** [comment]
Ah! Got it. That redundancy seems to work when Appending media to an item, but not when doing a Media import (create) to items that already have some media. I am not sure which case is going to be more common but perhaps it should do it for both?

**Comment by allanaaa** [comment]
I don't see any problems with Media ordering relative to the spreadsheet order, so that seems fine. 

I don't see anything that requires any new screenshots either, everything looks good for now.

**Comment by zerocrates** [comment]
Yeah, I don't think it applies for media creates. I'd have to look more closely though.

It's kind of a weird feature... I'd be happy with removing it also just for consistency. We should probably pull this out into another issue: I don't think it'll affect things for 2.5 and I'll lose it if it's in here.
