### ISSUE TITLE
"Automap" when unchecked still automaps

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/CSVImport#211]
I'm repeating a media-import process on 2.5.0 (develop) and so I unchecked the "Automap with simple labels" to save me some time. It doesn't work - all the column headings are still being automapped.

**Comment by zerocrates** [comment]
What are the column headers you were using for this sheet?

**Comment by allanaaa** [comment]
Nope, ignore me, I was confusing "simple" with "detailed". Although I wouldn't like anything to automap, sometimes ....
