### ISSUE TITLE
Testing: new "append" deduplication

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#222]
CSV Import's develop branch has updated code for the "append" import type. Append has code that tries to prevent "appending" a value that already exists to a resource, and the changes here focus on how that works.

How deduplication should work:
- Values in the imported file that are duplicates of values that already exist on the resource being updated should be ignored
- Values that already exist in a resource should always be left alone, exactly as they were, with the same public/private status, value annotations, etc.
- Values are only "duplicates" if they share the same data type and value: so literals need the same value text, for URLs it's the URL that matters, for resources, the ID of the resource being linked to. Values with different data types (text vs. URL vs. Numeric Data Types timestamp, etc.) are never duplicates of each other.
  - *Only* that main piece of data, the text/uri/resource ID, is used to determine if a value is unique. Different settings for value visibility and so on should have no effect: if the value is a duplicate then the imported value and all associated settings should just get ignored
- If a resource already has duplicate values, they should be left alone; this doesn't remove all duplicates, it just ignores duplicates that are in the import.

This should fix a bug in the previous CSV Import: this deduplication didn't work right when the values were linked resources (so, using the "Omeka resource" data type). The old version would allow 2 copies of the same value (2 links to the same other resource), and this one shouldn't. The old method also would remove preexisting duplicates from resources, and this one no longer should.

Doing "append" in succession with the same CSV and settings is one simple possible test, but coverage of some other scenarios like having the resources already have duplicates, or changing columns' data types between import runs, would also be useful.

Only appends are affected.

**Comment by katknow** [comment]
I believe this is working as expected!
