### ISSUE TITLE
imports not working, "$headersSent is deprecated" in Omeka core

### ISSUE THREAD

**Issue by mw0000** [omeka-s-modules/CSVImport#223]
Imports are not working. After running the import, nothing happens. The job is running, but it does not finish, and it is not in svimport/past-imports.

errors in the PHP logs:

`[Fri Nov 29 11:21:25.282805 2024] [proxy_fcgi:error] [pid 2099071:tid 2099469] [remote XXXXXX.88:48030] AH01071: Got error 'PHP message: PHP Deprecated:  Creation of dynamic property Laminas\\Http\\PhpEnvironment\\Response::$headersSent is deprecated in /data/XXXXXX/vendor/laminas/laminas-http/src/PhpEnvironment/Response.php on line 113', referer: https://XXXXXX/admin/job/594`

setup:

CSVImport 6.2
Omeka S 4.1.1
PHP 8.4.1 (cli) (built: Nov 25 2024 18:03:47) (NTS)
with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
apcu, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dom, exif, FFI, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, intl, json, ldap, libxml, mbstring, mcrypt, memcached, msgpack, mysqli, mysqlnd, OAuth, openssl, pcre, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, random, readline, redis, Reflection, session, shmop, SimpleXML, soap, sockets, sodium, solr, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, Zend OPcache, zip, zlib

**Comment by zerocrates** [comment]
Closing this in favor of your forums post.
