### ISSUE TITLE
No log on failed but complete imports

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#24]
When an import doesn't go through, the status is completed and there is no error log (and thus no hint on the admin dashboard for what went wrong).
![screen shot 2016-04-19 at 2 32 20 pm](https://cloud.githubusercontent.com/assets/2314070/14650912/9b0a34a2-063b-11e6-8254-f3c1a5e12993.png)

**Comment by mebrett** [comment]
If you look at http://dev.omeka.org/omeka-s/admin/job/210, you can see that it's marked as "Completed" but it didn't actually import anything. The importer/setup had problems getting files from uploads.wikimedia and no data got added at all (instead of adding the elements and skipping the media)

```
2016-04-19T18:58:50+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:423
Errors:
{
    "o:media": [
        {
            "error": [
                "Unable to enable crypto on TCP connection upload.wikimedia.org: make sure the \"sslcafile\" or \"sslcapath\" option are properly set for the environment."
            ]
        }
    ]
}
```

**Comment by patrickmj** [comment]
I updated some of the config so it should work better with wikipedia and other ssl sites. I also switched it so it no longer continues importing when there's an error with an item, so if something breaks the status should now be error.

**Comment by mebrett** [comment]
Working better with wikipedia, but I'm still not getting an error status when imports break.

**Comment by zerocrates** [comment]
The problem here is that the importer doesn't actually check the response from the API to see if it's a success or failure.

**Comment by patrickmj** [comment]
ah. indeed. I've been confused about where and how stuff like that gets handled
