### ISSUE TITLE
Variable success of oEmbed media

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#25]
Not sure why, but flickr succeeds and vimeo fails.

Both csvs are very simple, the flickr one adds all three items and the vimeo one did not create a single item, even when it was only the header row and a row with title and url for media.

[Archive.zip](https://github.com/omeka-s-modules/CSVImport/files/228164/Archive.zip)

**Comment by mebrett** [comment]
TED talk oEmbed CSV worked, too.

**Comment by patrickmj** [comment]
the vimeo file appears to have had odd line ending encoding specific to Mac. I should check that along with UTF-8 encoding
