### ISSUE TITLE
Resource Class does not map properly

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#28]
I've tried with two different DC class terms (Text and Moving Image) in separate CSVs (one class per CSV). In both instances, all items were successfully created but all were assigned the class "Agent". 

Jobs 248 and 251 on the shared install. 
[MapClass.zip](https://github.com/omeka-s-modules/CSVImport/files/228574/MapClass.zip)

**Comment by patrickmj** [comment]
It's a bug that it got mapped to Agent, but the kind of value to use is something from the list of Classes under the vocabulary pages. In the example of the Movies file, that'd be `dctype:` to match what's in the Classes column under Dublin Core Type on the Vocabularies page.

Not really sure how to point people to that. Maybe explanatory text under each of those buttons for mappings, but that could get ugly, too.

**Comment by mebrett** [comment]
So, what you're saying is that it should start with dctype? So 'dctype:Text' not 'Text'?

**Comment by patrickmj** [comment]
Yep! Or, for whatever class, go with whatever is listed under the classes list.

That also reminds me of something I might've forgotten to add in to the original testing issue, but automapping works a similar way. That is, a column in the CSV with heading `dcterms:title` should get automapped to DC Title.

**Comment by mebrett** [comment]
Seems to be working now. It will require some explanation in the documentation, but is there room for a short note "include dcterms: prefix" for importing class terms somewhere on the page?

**Comment by patrickmj** [comment]
Maybe. I'm not entirely sure that on the page is the right place, since if they've already gotten to the page, they've already put together the CSV, and will have to go back anyway. Better logging of issues like that are definitely in order, though.

**Comment by patrickmj** [comment]
Newest master branch should have better logging for this, and non-matching owner and template name values
