### ISSUE TITLE
Import throws error referencing non-object

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#30]
Error message in job log is `Fatal error: Call to a member function label() on a non-object in /websites/omekadev/home/www/omeka-s/modules/CSVImport/src/Mapping/ItemMapping.php on line 123` (hooray error logging working!)

File is attached as a zip. Process is as follows: 

- Import CSV. 
- Multivalue separator is ;
- First 3 columns should be automapped. 
- Map Publisher to publisher.
- Owner maps to user owner email
- Class maps to resource class term
- Template maps to Resource Template Name
- URL File and YouTube are media (separate columns)
- Item Set is the Item Set ID

The job should hit an error and stop before importing a single item.

For previous attempts of this CSV see jobs: 270, 273, 275 on the shared install. 
[CSV maker - Dickensia.csv.zip](https://github.com/omeka-s-modules/CSVImport/files/230618/CSV.maker.-.Dickensia.csv.zip)

**Comment by zerocrates** [comment]
That's definitely a bug, but are the columns in the sample CSV meant to be kind of messed up? (A bunch of the "template" entries are actually classes, etc.)

**Comment by mebrett** [comment]
In the original file the templates are properly the template names from the install - wonder if it's get borked in the export.

**Comment by zerocrates** [comment]
Whatever the reason, the one attached to this issue is wrong, like a column got dropped somewhere for the last few rows.

**Comment by zerocrates** [comment]
Actually I see what's happening, OpenOffice is splitting the file on both comma and semicolon.

**Comment by zerocrates** [comment]
The _actual_ problem is the one blank cell in the template column. The mapping isn't skipping over the blank one, so it's trying to find a template with a blank label. If you fill that one in, the file imports fine.

Blank should probably always be skipped, but there's the separate issue of whether these kinds of failed mappings should cause an error or not (say, if you do put in a template that doesn't exist).
