### ISSUE TITLE
2nd  run through CSVImport

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#44]
For the second run through CSVImporter, first uninstall the module, then update the master branch, then install it again.

There's now the feature to import users to look at. CSV file takes columns for name, email address, and role. Those new users should get an email when they are created.

The files that didn't work first time around should now either work, or give more useful error messages.

There's also a variety of changes to the interface

**Comment by mebrett** [comment]
I can't seem to map elements? On shared install (dev.omeka.org/omeka-s). Branch master of the importer, branch develop of S and up-to-date with both.

When I add a CSV and got to the Map to Omeka S data tab, I see this:
![csvimporter20160524](https://cloud.githubusercontent.com/assets/2314070/15516115/4efac4ce-21bf-11e6-9969-415fe25152bd.png)

No actions appear to be triggered when I try clicking on Properties, Media Import, or Item Data. 

(If I import the unmapped csv, it will create a number of empty items equal to the number of rows in the CSV, with the right owner and template)

**Comment by patrickmj** [comment]
oops. missed putting a fix for that into master. should be fixed on master now.

**Comment by mebrett** [comment]
Just a UI note - I keep hitting Import before I map (not used to the two tabs yet)
