### ISSUE TITLE
Import/Map Users unavailable

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#46]
Opened the Importer module, selected a users file, selected Users from the dropdown (of Users/Items). When I click "Next" I get the following error:

`Notice: Undefined variable: serviceLocator in /websites/omekadev/home/www/omeka-s/modules/CSVImport/src/Form/MappingForm.php on line 80 Catchable fatal error: Argument 1 passed to Omeka\Form\Element\ResourceSelect::__construct() must implement interface Zend\ServiceManager\ServiceLocatorInterface, null given, called in /websites/omekadev/home/www/omeka-s/modules/CSVImport/src/Form/MappingForm.php on line 80 and defined in /websites/omekadev/home/www/omeka-s/application/src/Form/Element/ResourceSelect.php on line 19`

On shared install (dev/omeka-s) importing file that looks like this
`email,role,display name
[email one],Editor,Megan1
[email two],Editor,Megan2`

**Comment by patrickmj** [comment]
should be fixed in master
