### ISSUE TITLE
Item Set- required field

### ISSUE THREAD

**Issue by jannellelegg** [omeka-s-modules/CSVImport#54]
Did some user testing today - could we add a red star (or some other indication) to the Item Set option on the import page? Without an Item Set selected, the import fails (for both Item and User imports). 

We've added a note to the user documentation, but a visual reminder on that page would be helpful.

![csvimport_userbasic](https://cloud.githubusercontent.com/assets/5897725/19734861/38ac0ba6-9b77-11e6-8732-2bcfb08cda80.png)

**Comment by patrickmj** [comment]
The intended behavior is that selecting an Item Set is not actually required, so this is a bug of a different color.

**Comment by patrickmj** [comment]
@jannellelegg this is ready for another look on develop, on these points:

1) item set is not required
2) one item set works
3) multiple item sets work
4) importing users doesn't show item set an other fields that are only relevant to items

**Comment by jannellelegg** [comment]
Update seems to have resolved some of the issues, I can confirm:
1) item set not required
2) one item set works
4) importing users doesn't show item set or other fields only relevant to items

Additional testing is needed on assigning multiple item sets - I've not been able to successfully import to multiple sets.

**Comment by patrickmj** [comment]
Curious. Works on my install. Anything in the logs?

**Comment by jannellelegg** [comment]
Did some additional testing - it looks like it was an issue with the media path that was causing the failure. This is resolved :)
