### ISSUE TITLE
Past Imports columns scrunch up when there's a problem

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#59]
When there's a problem with an import, it still happens, but tries to be helpful and notify the user. But, the column sizes make it scrunch up the column headers. Seems like there's something limiting the width to something, but not sure if this should be a fix specific to the module, or something more general in the core styling -- seems like a question for @kimisgold 

(Quick way to reproduce the page: import a CSV file and have a column for Item Set Id that doesn't match an existing Item Set when you try to map it.)

![scrunchycsvpastimports](https://cloud.githubusercontent.com/assets/153262/20366312/6b5ba2da-ac18-11e6-8f90-7e75c844548a.png)

**Comment by kimisgold** [comment]
This is the nature of tables: their column widths will try to accommodate those with the largest amount of content, assign minimum widths based on the narrowest content in columns, and make the widths as equal as possible considering those other goals. I can't make assumptions on modules' table contents, so any width styles should be specific to the module.

For this module, comment seems like a complicating column. It should generally be empty, but when it's not, it is likely to have more content then any other column. Could you provide a list of all the possible comments that can appear in that area? I think my ideas for how to address this are dependent on that.

(Tangentially, your screenshot looks like you need to do a hard refresh: I made a recent change to the default table border styles.)

**Comment by patrickmj** [comment]
Thanks. The way this (and some other modules) are set up, comments could be anything. They are intended as notes about what the user doing the import thinks should happen in the import process. In this case, it's the module itself adding its own messages to the comments in an attempt to be helpful, but the import settings allow anything.

Also, not seeing differences after hard refreshes, but that might just be my weak eye for such things.

Sounds like the modules, then, should impose their own limits to the width of the column?
