### ISSUE TITLE
Quick brokenness check

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#63]
@mebrett could I ask you (or other testers) to confirm that CSVImport still works as expected? It's not working for me, but it's possible that a laptop update broke things. So, looking for whether it really is a problem on my end or not. Thanks.

**Comment by mebrett** [comment]
Any particular branch of CSV import or core?

**Comment by patrickmj** [comment]
Maybe start with master of both. Eventually we'll need to check develop of both, though.

**Comment by mebrett** [comment]
On develop of both it works fine.

**Comment by patrickmj** [comment]
Thanks! Looks like it was indeed a bad update on my laptop. Grr! All better now!
