### ISSUE TITLE
Make CSVImport and FileSideload play nicely together

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#64]
Files uploaded via FileSideload should be available for import/matching up in a CSV file import

**Comment by patrickmj** [comment]
- [ ] Add sideload case to MediaIngester
- [ ] Look up FileSideload's path setting
- [ ] Figure out how to do the sideload by copying from FileSideload

**Comment by zerocrates** [comment]
I think it might make sense to have this work in the reverse fashion: have FileSideload contain the code that adds itself to the list of media the importer imports.

All FileSideload should basically have to do is get the filename from the cell then handle the ingest the way it handles any other sideload.

**Comment by patrickmj** [comment]
That would likely require change in CsvImport, as it currently has to do a switch/case on the ingester type to make sure the data for the request is as it should be. Does look like I don't have to duplicate from FileSideload, but still have the changes in CsvImport, just with a check on whether FileSideload is active.
