### ISSUE TITLE
Ability to import relational data when adding items

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#65]
For example: if I'm importing my CSV of Sherlock Holmes stories, I could go ahead and create an Omeka S item for Arthur Conan Doyle. Then when I import the CSV, I use the item number for Doyle in place of his name and the import will create the items such that Item:ArthurConanDoyle is creator of each imported item.

**Comment by patrickmj** [comment]
Would you imagine this as a checkbox on the mapping page to specify that it's a relation, not a text string? It's a safe assumption for creator, but something like relation could easily be ambiguous.

**Comment by mebrett** [comment]
A checkbox would make sense, or an additional button under Options ("import as url reference", "import relation to existing item")

**Comment by patrickmj** [comment]
That does make more sense
