### ISSUE TITLE
Import clobbering data types in resource templates

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/CSVImport#66]
My resource template designated that some properties were to be URIs, but the import makes everything text or default.

See Source Document property here: http://jesuitplantationproject.org/omeka-s/s/jpp/item/275

**Comment by zerocrates** [comment]
Patrick can chime in to confirm or deny, but my understanding is that the template option merely _sets_ the template on the created items for future usage, it doesn't apply the template's settings when creating the initial items. It only cares what the mapping settings for the column are.

**Comment by sharonmleon** [comment]
Ahh..... that's a bummer.

**Comment by patrickmj** [comment]
Yep. It sets the template, but doesn't try to reach in and apply that to the mappings. That can be set on the mapping page, though.
