### ISSUE TITLE
Look into language mapping

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#69]
Per https://forum.omeka.org/t/internationalized-omeka-s/3154/2 it'd make sense to add a property mapping option for language.

Would probably call for replicating the manual language chooser at the bottom of the property selector mapping, with a button to confirm and add it to the mappings.

After that, the PropertyMapper would read that similarly to how it read the URL and Resource reference settings, and just add that to the json created.

Related forum post: https://forum.omeka.org/t/bilingual-content-internationalisation/2116/2

**Comment by hajoki** [comment]
The import with different languages worked just fine, I just had to edit` config/module.ini` where I changed `omeka_version_constraint = "^1.0.0-beta3" ` 
to `omeka_version_constraint = "^1.0.0-beta" `
Thanks a lot!

**Comment by patrickmj** [comment]
Excellent! Eventually, the next release might still have that `beta3` constraint due to significant changes in the API
