### ISSUE TITLE
De-float the actions div

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#76]
From the latest meeting, @zerocrates thinks that the solution I put in for fixing the display of the actions div is problematic. So, I'll need to consult with him and @kimisgold to find a better solution. 

Whatever the change is, it will apply across many modules, probably with some variation for each. Thus, I don't know how much the modules should do quirky things to make it work, and how much core styling should have the mechanisms to work in different module places.

But, CSVImport seems like a reasonable place to try to bring everything together for a first attempt, since it only asks for a CSV file to get started.

I'm putting John and Kim  in here as assignees just 'cuz it seems like it will call for pulling our perspectives together.

**Comment by kimisgold** [comment]
My current approach with the actions list works from the idea that 1) they are part of a bigger row and 2) they should sit at the row's right edge. I used to work with floats, absolute positioning, and displaying parts of the actions list as inline-blocks, but it ended up with a lot of cruddy position hacks and inconsistent margins. Flexbox has been the replacement for all of the above, and I currently have it applied to the actions list itself, as well as the row container where applicable.

CSVImport has a lot going on, so most likely there'll be a bunch of styles specific to the module. Hopefully the above explanation helps provide general guidelines for updating the others.

**Comment by patrickmj** [comment]
Looks like putting a `flex` just on each li of mappings worked, but might need checks across browsers and devices. 

See https://github.com/omeka-s-modules/CSVImport/commit/51bcb6273d60dcd650b49d117672cb3795b69fe5
