### ISSUE TITLE
When sidebar for mapping opens, buttons change sizes

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#84]
Actually they don't change sizes, the placement just exposes the different sizes.

**Comment by patrickmj** [comment]
@kimisgold and @zerocrates : want to ask if this is fine or not for the button widths. Basically, it's whether I should try to force them to the same width, or let them just size by the content. The buttons open different sidebars for mapping options. Depending on the horizontal space available they place differently. The first two seem fine, just wonder if the last (small horizontal space) seems like it calls for a change.

Lots of horizontal space:
![widemappingoptions](https://user-images.githubusercontent.com/153262/29084321-a2b323a6-7c39-11e7-8afe-174d2b3dd45a.png)


Medium horizontal space:
![mediummappingoptions](https://user-images.githubusercontent.com/153262/29084328-aa262dae-7c39-11e7-9919-c1f0223a0210.png)


Small horizontal space:
![smallmappingoptions](https://user-images.githubusercontent.com/153262/29084341-b1ae9c32-7c39-11e7-906c-c7d60f550a7c.png)

**Comment by patrickmj** [comment]
With Mapping installed, and small space:

![mapmappingoptions](https://user-images.githubusercontent.com/153262/29085120-3d20318e-7c3c-11e7-9784-b98f9e89d303.png)

**Comment by kimisgold** [comment]
I lean towards equal width, if only because the tiny mapping button looks awkward to me compared to all the others even regardless of its inline layout in that last screenshot.
